# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenSpace' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

   pod 'GoogleSignIn'
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   #GoogleAnalytics + GoogleAppMeasurement crashed due to version mismatch
   pod 'GoogleAppMeasurement', '~> 5.2.0'
  # Pods for OpenSpace
  target 'OpenSpace-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenSpaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
